
/***********************************************************************************************************
 * Produced by App Advisory	- http://app-advisory.com													   *
 * Facebook: https://facebook.com/appadvisory															   *
 * Contact us: https://appadvisory.zendesk.com/hc/en-us/requests/new									   *
 * App Advisory Unity Asset Store catalog: http://u3d.as/9cs											   *
 * Developed by Gilbert Anthony Barouch - https://www.linkedin.com/in/ganbarouch                           *
 ***********************************************************************************************************/


using UnityEngine;
using System.Collections;
using UnityEngine.UI;
public class ButtonBase : MonoBehaviour 
{
	Button b;

	Text t;

	void OnEnable()
	{
		b = GetComponent<Button>();
		b.onClick.AddListener(OnClicked);

		t = GetComponentInChildren<Text>();
	}

	void OnDisable()
	{
		b.onClick.RemoveAllListeners();
	}


	public virtual void OnClicked(){}

	public void SetText(string s)
	{
		t.text = s;
	}
}
